apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gas-frontend
  namespace: gas
  labels:
    app.kubernetes.io/name: gas-frontend
    app.kubernetes.io/part-of: ghana-audit-service
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - audit.gov.gh
      secretName: gas-tls
  rules:
    - host: audit.gov.gh
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gas-frontend
                port:
                  number: 80
