apiVersion: v1
kind: Service
metadata:
  name: gas-frontend
  namespace: gas
  labels:
    app.kubernetes.io/name: gas-frontend
    app.kubernetes.io/part-of: ghana-audit-service
spec:
  selector:
    app.kubernetes.io/name: gas-frontend
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
