apiVersion: v1
kind: Secret
metadata:
  name: gas-secrets
  namespace: gas
  labels:
    app.kubernetes.io/part-of: ghana-audit-service
type: Opaque
stringData:
  DB_USER: "${DB_USER}"
  DB_PASSWORD: "${DB_PASSWORD}"
  JWT_SECRET: "${JWT_SECRET}"
  NUXT_API_SECRET: "${NUXT_API_SECRET}"
  ANALYTICS_IP_SALT: "${ANALYTICS_IP_SALT}"
---
apiVersion: v1
kind: Secret
metadata:
  name: gas-db-credentials
  namespace: gas
  labels:
    app.kubernetes.io/part-of: ghana-audit-service
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
  MYSQL_USER: "${DB_USER}"
  MYSQL_PASSWORD: "${DB_PASSWORD}"
  MYSQL_DATABASE: "ghana_audit_service"
