import { createReadStream } from 'node:fs'
import { stat } from 'node:fs/promises'
import { extname, join } from 'node:path'
import { createError, sendStream, setHeader } from 'h3'
import type { H3Event } from 'h3'
import { downloadBlob } from './blobStorage'
import { getUploadBaseDir } from './fileUpload'
import { resolvePublicAsset } from './publicFiles'

/**
 * Serving for runtime-uploaded images (`/uploads/{images,thumbnails}/*`).
 *
 * Nitro's static handler resolves assets against a manifest generated at BUILD
 * time (`#nitro-internal-virtual/public-assets`), so a file written after
 * `nuxt build` — every admin upload — is never served from it, whichever
 * directory it lands in. Because the root public dir has `baseURL: '/'` it is
 * excluded from `publicAssetBases`, so `isPublicAssetURL()` is false for these
 * paths and the miss falls through to route handlers instead of 404ing. That
 * fallthrough is what lets these routes exist.
 *
 * Baked and dev-time files still hit the static handler first, so this only
 * ever runs for manifest misses.
 */

/** MIME types for the extensions `uploadConfigs.image`/`.thumbnail` accept. */
const IMAGE_CONTENT_TYPES: Record<string, string> = {
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.png': 'image/png',
  '.webp': 'image/webp',
  '.gif': 'image/gif'
}

/**
 * Names are generated by `fileUpload.generateFilename()` as
 * `<yyyymmdd>-<uuid>.<ext>`. The strict charset (no dots, slashes or escapes
 * before the extension) is also what rules out traversal in the resolved path
 * and the blob key.
 */
const UPLOAD_NAME_PATTERN = /^[A-Za-z0-9-]+\.(jpe?g|png|webp|gif)$/i

/** Names embed a UUID, so content never changes under a given URL. */
const CACHE_CONTROL = 'public, max-age=86400, immutable'

const notFound = () => createError({ statusCode: 404, statusMessage: 'Not Found' })

/**
 * Stream `/uploads/<directory>/<name>` from disk, falling back to Azure Blob.
 *
 * Disk first because `uploadConfigs.image` is disk-backed and the uploads
 * directory is a ReadWriteMany share in production, so the file is visible to
 * every replica. Blob is tried second so this keeps working if a config is
 * switched to `backend: 'blob'` (as `thumbnail` effectively is in production).
 */
export async function serveUploadedImage(
  event: H3Event,
  directory: 'images' | 'thumbnails',
  name: string
) {
  if (!UPLOAD_NAME_PATTERN.test(name)) {
    throw notFound()
  }

  const extensionType = IMAGE_CONTENT_TYPES[extname(name).toLowerCase()]

  // Where persistUpload() actually wrote (honours UPLOAD_DIRECTORY), then the
  // dev/production public layouts for files baked or seeded onto the share.
  const candidates = [
    join(getUploadBaseDir(), directory, name),
    resolvePublicAsset(`/uploads/${directory}/${name}`)
  ]

  for (const candidate of candidates) {
    if (!candidate) continue
    const stats = await stat(candidate).catch(() => null)
    if (stats?.isFile()) {
      setHeader(event, 'Content-Type', extensionType)
      setHeader(event, 'Content-Length', stats.size)
      setHeader(event, 'Cache-Control', CACHE_CONTROL)
      return sendStream(event, createReadStream(candidate))
    }
  }

  const blob = await downloadBlob(`uploads/${directory}/${name}`)
  if (!blob) {
    throw notFound()
  }

  setHeader(event, 'Content-Type', blob.contentType || extensionType)
  if (blob.contentLength > 0) {
    setHeader(event, 'Content-Length', blob.contentLength)
  }
  setHeader(event, 'Cache-Control', CACHE_CONTROL)

  return sendStream(event, blob.stream)
}
